---
title: "Importance Simulation"
author: "Peter Menzies"
date: "2/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Standard packages
library(tidyverse)
library(here)
library(patchwork)
library(psych)
library(kableExtra)

## Machine Learning packages
library(caret)
library(spatialRF)
library(randomForest)
library(party)
library(partykit)
library(permimp)
library(ranger)
```

```{r}
gen_regr <- function(n) {
  
    x1 <- sample.int(5, n, replace = TRUE)
    x2 <- sample.int(3, n, replace = TRUE)
    x3 <- sample.int(4, n, replace = TRUE)
    x4 <- sample.int(5, n, replace = TRUE)
    x5 <- sample.int(6, n, replace = TRUE)
    x6 <- sample.int(7, n, replace = TRUE)
    x7 <- sample.int(8, n, replace = TRUE)
    x8 <- sample.int(9, n, replace = TRUE)
    x9 <- sample.int(10, n, replace = TRUE)
    x10 <- sample.int(11, n, replace = TRUE)
    
    y <- sample.int(10, n, replace = TRUE) + runif(n) * x1 * 0.5
    
    sim_df <- tibble(
      x1 = x1,
      x2 = x2,
      x3 = x3,
      x4 = x4,
      x5 = x5,
      x6 = x6,
      x7 = x7,
      x8 = x8,
      x9 = x9,
      x10 = x10,
      y = y
    )
      
    return(sim_df)
    
}
```


```{r}
sim_df <- gen_regr(1000)
```

```{r}
rf_perm <- tribble(~"x1", ~"x2", ~"x3", ~"x4", ~"x5", ~"x6", ~"x7", ~"x8", ~"x9", ~"x10")
permimp <- tribble(~"x1", ~"x2", ~"x3", ~"x4", ~"x5", ~"x6", ~"x7", ~"x8", ~"x9", ~"x10")
ranger_imp <- tribble(~"x1", ~"x2", ~"x3", ~"x4", ~"x5", ~"x6", ~"x7", ~"x8", ~"x9", ~"x10")
```


```{r}
system.time(
  
  for (i in seq(1, 100)) {
  
    df <- gen_regr(1000)
    
    rf <- randomForest(formula = y ~ .,
                       data = df,
                       replace=TRUE,
                       importance=TRUE,
                       keep.forest=TRUE,
                       keep.inbag=TRUE)
    
    ranger <- ranger(formula = y ~ .,
                       data = df,
                       replace=TRUE,
                       importance="impurity_corrected")
    
    rf_perm_rank <- rf$importance %>% 
      data.frame() %>% 
      rownames_to_column("variable") %>% 
      mutate(rank = rank(-X.IncMSE)) %>% 
      select(variable, rank) %>% 
      pivot_wider(names_from = variable, values_from = rank)
    
    rf_perm <- rf_perm %>% 
      rbind(rf_perm_rank)
    
    ranger_imp_rank <- ranger$variable.importance %>% 
      data.frame() %>% 
      rownames_to_column("variable") %>% 
      mutate(rank = rank(-.)) %>% 
      select(variable, rank) %>% 
      pivot_wider(names_from = variable, values_from = rank)
    
    ranger_imp <- ranger_imp %>% 
      rbind(ranger_imp_rank)
    
    permimp_out <- permimp(rf, 
                   #conditional=TRUE,
                   do_check=FALSE, progressBar=FALSE)

    permimp_rank <- permimp_out$values %>% 
      data.frame() %>% 
      rownames_to_column("variable") %>% 
      mutate(rank = rank(-.)) %>% 
      select(variable, rank) %>% 
      pivot_wider(names_from = variable, values_from = rank)
    
    permimp <- permimp %>% 
      rbind(permimp_rank)
    
  }
)
```


# ```{r}
# ranger <- ranger(formula = y ~ .,
#                    data = sim_df,
#                    replace=TRUE,
#                    importance="impurity_corrected")
# 
# ranger_imp_rank <- ranger$variable.importance %>% 
#   data.frame() %>% 
#   rownames_to_column("variable") %>% 
#   mutate(rank = rank(-.)) %>% 
#   select(variable, rank) %>% 
#   pivot_wider(names_from = variable, values_from = rank)
# ```
# 
# ```{r}
# rf <- randomForest(formula = y ~ .,
#                    data = sim_df,
#                    replace=TRUE,
#                    importance=TRUE,
#                    keep.forest=TRUE,
#                    keep.inbag=TRUE)
# 
# rf_rank <- rf$importance %>% 
#   data.frame() %>% 
#   rownames_to_column("variable") %>% 
#   mutate(rank = rank(-X.IncMSE)) %>% 
#   select(variable, rank) %>% 
#   pivot_wider(names_from = variable, values_from = rank)
# ```
# 
# ```{r}
# permimp_out <- permimp(rf, 
#                    #conditional=TRUE,
#                    do_check=FALSE, progressBar=FALSE)
# 
# permimp_rank <- permimp_out$values %>% 
#   data.frame() %>% 
#   rownames_to_column("variable") %>% 
#   mutate(rank = rank(-.)) %>% 
#   select(variable, rank) %>% 
#   pivot_wider(names_from = variable, values_from = rank)
# ```

```{r}
mean(rf_perm$x1)
mean(ranger_imp$x1)
mean(permimp$x1)
```



