---
title: "Sagehen Data Exploration"
author: "Peter Menzies"
date: "1/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(randomForest)
library(randomForestExplainer)
```

```{r}
df <- read_csv(here("data", "sageres.csv"))
```

```{r}
print(nrow(df))
print(ncol(df))

print(names(df))
```


```{r}
head(df)
```


```{r}
(unique(df$stratumID))
(unique(df$patchID))
(unique(df$zoneID))
```

```{r}
unique(df$month)
```


```{r}
df_apr <- df %>% 
  filter(month == 4, year == 2020)
```

```{r}
df_by_wy <- df %>% 
  group_by(wy, stratumID, clim, scen) %>% 
  summarise_if(is.numeric, mean) %>% 
  select(-day, -month, -year, -basinID, -hillID, -zoneID, -patchID)
```

```{r}
df_by_wy <- df_by_wy %>% 
  mutate(water_efficiency = npp / trans)
```

```{r}
df_wy_0 <- df_by_wy %>% 
  filter(clim == 0)

df_wy_2 <- df_by_wy %>% 
  filter(clim == 2)
```


```{r}
ggplot(df_wy_0, aes(x = rz_storage, y = water_efficiency)) +
  geom_point() + 
  geom_smooth(method = "lm")

ggplot(df_wy_2, aes(x = rz_storage, y = water_efficiency)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
ggplot(df_wy_0, aes(x = tmax, y = water_efficiency)) +
  geom_point() + 
  geom_smooth()

ggplot(df_wy_2, aes(x = tmax, y = water_efficiency)) +
  geom_point() + 
  geom_smooth()
```
## Random Forest Exploration

Comparing node purity increase among variables explaining npp

```{r}
rfout <- randomForest(formula = npp ~ tmax  + tmin + aspect + slope + clim + swe + scen + elev + precip,     
                 data = df_by_wy)

print(rfout)

# type = 2 arg gives output: mean decrease in node impurity (as opposed to type = 1 which gives mean decrease in accuracy)
purity <- rfout$importance %>%
  as.data.frame() %>%
  rownames_to_column("variable") %>% 
  rename("variable" = 1,"inc_node_purity" = 2) %>% 
  as_tibble()

purity <- purity[order(purity$inc_node_purity, decreasing = TRUE), ]

purity
```

*IncNodePurity* (increase in node purity) the total decrease in node impurities, measured by the Gini Index


```{r}
rfout_clim0 <- randomForest(formula = npp ~ tmax + tmin + aspect + slope + swe + scen + elev + precip,     
                 data = df_wy_0)

print(rfout_clim0)

purity_clim0 <- rfout_clim0$importance %>%
  as.data.frame() %>%
  rownames_to_column("variable") %>% 
  rename("variable" = 1,"inc_node_purity" = 2) %>% 
  as_tibble()

purity_clim0 <- purity_clim0[order(purity_clim0$inc_node_purity, decreasing = TRUE), ]

purity_clim0
```



```{r}
rfout_clim2 <- randomForest(formula = npp ~ tmax + tmin + aspect + slope + swe + scen + elev + precip,     
                 data = df_wy_2)

print(rfout_clim2)

purity_clim2 <- rfout_clim2$importance %>%
  as.data.frame() %>%
  rownames_to_column("variable") %>% 
  rename("variable" = 1,"inc_node_purity" = 2) %>% 
  as_tibble()

purity_clim2 <- purity_clim2[order(purity_clim2$inc_node_purity, decreasing = TRUE), ]

purity_clim2
```

```{r}
randomForestExplainer::explain_forest(randomForest::importance(rfout, type = 2))
```



